-- Create packages table
create table public.packages (
  id bigint generated by default as identity primary key,
  name text not null,
  duration_days integer not null,
  price numeric(10, 2) not null,
  created_at timestamp with time zone default now()
);

-- Enable RLS for packages
alter table public.packages enable row level security;

-- Public read access for packages
create policy "Enable read access for all users"
on public.packages for select
using (true);

-- Re-create licenses table with foreign keys
-- Drop existing table if needed (WARNING: DATA LOSS)
drop table if exists public.licenses;

create table public.licenses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id), -- Link to Supabase Auth User
  package_id bigint references public.packages(id),
  key_code text not null unique,
  hwid text,
  status text check (status in ('active', 'banned', 'expired')),
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- Enable RLS for licenses
alter table public.licenses enable row level security;

-- Policy: Users can view their own licenses
create policy "Users can view own licenses"
on public.licenses for select
using (auth.uid() = user_id);

-- Policy: Users can update their own licenses (e.g. for HWID reset?)
-- Restricting update to only HWID would require a trigger or separation, 
-- but for simplicity allowing update if user owns it.
create policy "Users can update own licenses"
on public.licenses for update
using (auth.uid() = user_id);

-- Policy: Allow API (service role) to do everything? 
-- In Supabase, service role bypasses RLS, so we don't need explicit policy for it usually.
-- But for our public API route, it uses the anon key usually? 
-- The user said "Enable Row Level Security (RLS) but allow public read/write access for now (for development)."
-- Let's keep the development policy to avoid permission errors during testing if auth isn't fully set up.

create policy "Enable all access for all users (DEV)"
on public.licenses
for all
using (true)
with check (true);

-- Function to generate license key (Same as before)
create or replace function generate_license_key()
returns text
language plpgsql
as $$
declare
  chars text[] := '{A,B,C,D,E,F,G,H,J,K,L,M,N,P,Q,R,S,T,U,V,W,X,Y,Z,2,3,4,5,6,7,8,9}';
  result text := 'VIP-';
  i integer;
begin
  for i in 1..4 loop
    result := result || chars[1+random()*(array_length(chars, 1)-1)];
  end loop;
  result := result || '-';
  for i in 1..4 loop
    result := result || chars[1+random()*(array_length(chars, 1)-1)];
  end loop;
  return result;
end;
$$;

-- Seed Data
insert into public.packages (name, duration_days, price) values
('Weekly Pass', 7, 9.99),
('Monthly Pass', 30, 24.99),
('Lifetime Access', 3650, 199.99);
